--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: wpapp-deploy 
  labels: 
    app: wp 
    name: wpapp-deploy 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: wp
      name: wpapp-po
  template:
    metadata:
      name: wpapp-po 
      labels:
        app: wp
        name: wpapp-po 
    spec:
      containers:
      - name: wpapp-container
        image: wordpress:5 
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wpapp-cm
        - secretRef:
            name: wpapp-secret
        ports:
        - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: wpapp-svc 
  labels: 
    app: wp
    name: wpapp-svc
spec:
  type: ClusterIP 
  selector:
    app: wp 
    name: wpapp-po
  ports:
  - port: 80 
    targetPort: 80

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: wpapp-ing 
  labels:
    app: wp 
    name: wpapp-ing 
spec:
  ingressClassName: nginx 
  rules:
  - host: tenant-146.190.4.104.nip.io
    http: 
      paths: 
      - path: /
        pathType: Prefix 
        backend:
          service: 
            name: wpapp-svc
            port: 
              number: 80