volumes:
  my-data:

networks:
  app-net:

services:
  nwdb:
    image: stackupiss/northwind-db:v1
    volumes:
    - my-data:/var/lib/mysql
    networks:
    - app-net

  nwapp:
    image: stackupiss/northwind-app:v1
    ports:
    - 8080-9000:3000
    environment:
    - DB_HOST=nwdb
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - app-net