apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../demo02

namePrefix: kuz-
nameSuffix: -k8s

commonLabels:
  deployDate: mar-31-2022

replicas:
- name: dov-deploy 
  count: 1 